### ISSUE TITLE
Random fallout shelters cause null pointer, player.dat corruption (Plugins for Forestry config missing)

### ISSUE THREAD

**Issue by overclock22** [mushroomhostage/exphc#85] opened 2012-08-11 20:59 UTC
Me and an associate have found a rash of fallout shelter, all in interesting condition but one caused us both to crash when opening the top or bottom set of one corners chests. 

Upon exploding them they crash everyone in the area not just who opened it. After many tries i got back in.

I think it may have caused ghost assassins character to break. 

Curiosity has goten the better of me and i blew up the other chest since the items became stable for me but again it cause a crash just looking in the direction of the fallen loot. 

I still have yet to see ghost get back in but he has tried. 

Its very interesting when I look towards the items It looks like it exploded into potions but it may have been the potion chest next to it. Before crashing I also saw plants and wireless receiver stuff. 

a much later edit: Ghostassassins character .dat is definitely glitched out, chain disconnects from different clients.

**Comment by mushroomhostage** [comment] 2012-08-12 02:26
This could have been caused by an invalid item in the generated chests. The loot groups I used are defined here: https://github.com/mushroomhostage/CakesMinerApocalypse/blob/master/src/me/cakenggt/CakesMinerApocalypse/CakesMinerApocalypse.java#L180 and here: https://github.com/mushroomhostage/exphc/blob/master/1.2.5/plugins/CakesMinerApocalypse/config.yml

I did remove MineFactory Reloaded lately, and if any of its items were in these chests it could cause this problem, but no generated vaults had MFR items..

The 'mixedmod' group is most suspicious: https://github.com/mushroomhostage/CakesMinerApocalypse/blob/master/src/me/cakenggt/CakesMinerApocalypse/CakesMinerApocalypse.java#L235

Its block IDs have since been reused. 126 is now Wireless Receiver, 127 is Nether Coal, 214 is Thatched Slab and 215 is Allium Drumstick – and I see both Thatched Slab and Allium Drumstick in ghost's inventory. I was able to login with his .dat just fine.. the item drops from the broken chest have since expired, though.

I bet this is the problem: 

```
        "1x567",        // Animal Bikes - cow bike
        "1x567;1",      // Animal Bikes - spider bike
        "1x567;5",      // Animal Bikes - wolf bike
        "16x569",       // Animal Bikes - rawhide
```

Even though its nonfunctional, I left Animal Bikes in for compatibility, and what'd you know, they go and change their item IDs on me. These items are now: 27016, 27017, 27021, 27015 (all without any metadata).

Can I get a crash report from Ghostassasin?

**Comment by overclock22** [comment] 2012-08-12 02:33
I dont know him too well, ill tell him to drop it on mcport if hes capable.

I didn't pick up any of the items but just looking at them till they expired kept me offline. Im sure hes very happy to be back.

Why did you take out the minefactory, i kept looking for them then realized they were gone. Too much free loot floating around?

**Comment by mushroomhostage** [comment] 2012-08-12 02:34
OK I fixed Ghost's player dat, turns out it was the Thatched Slab (214) and Allium Drumstick (215) causing the crashes. 

But they shouldn't be.. both items display correctly on my client just fine. I'm thinking the client configs for Plugins for Forestry are not correct.. may have not included it properly in the client setup. Looking into it, but meanwhile would you be able to pastebin an NEI item dump here? (inventory > Options > Block/Item ID Settings > Dump ID Map Now). If the IDs differ that will confirm that is the issue.

**Comment by mushroomhostage** [comment] 2012-08-12 02:40
Took out MFR because sadly it was incompatible with the newer version of Forge, which was required by the new mods. I think it has since been updated, but, is still buggy (hammers can't reorient machines, etc.). Also it has its own "steel", which is Forge-ore-dictionaried to Refined Iron from IC2, but is confusingly completely separate from and not interchangeable with Railcraft's steel (which is a lot harder to make, requiring a blast furnace). It wasn't used much either, though I admit the conveyer belts were quite nifty.

Anyways I know the problem. Turns out I forgot to include _any_ client configs for Plugins for Forestry, whoops. This means the block IDs are all mismatched. Will have an new update out soon to fix this.

edit: and the changed Animal Bikes IDs should not be a problem since the server does not know about them either - the Plugins for Forestry 214,215 blocks were mismatched on client/server, causing this crash

**Comment by mushroomhostage** [comment] 2012-08-12 02:56
1.2.5rev5b includes config/densoflionsx

**Comment by overclock22** [comment] 2012-08-12 03:03
mcport not loading for me zzzz

Would it be possible for you to upgrade the force field mod? Ive been overlooking the ic2 page and it looks like the systems a lot different and more sensible now. 

Keep up the excellent work bro.

**Comment by mushroomhostage** [comment] 2012-08-12 16:13
Possible, but there are two different forcefield mods – [Thunderdark MFFS v2](http://forum.industrial-craft.net/index.php?page=Thread&threadID=1292) and [Immibis Modular Forcefields](http://forum.industrial-craft.net/index.php?page=Thread&threadID=6874). Currently have Immibis Modular Forcefields, Thunderdark's version has the new stuff. I'd probably have gone with Thunderdark's had it came out first, but problem is if I switch from Immbis' now, everyone would need to redo their forcefields (the blocks and items are not compatible, etc.). So I think we're stuck with this mod until there is a reasonable way to convert it.

Anyways, this missing Plugins for Forestry config error causing chests containing those items to crash the client, should now be fixed with the latest client update - closing this issue.

**Closed as completed by mushroomhostage** 2012-08-12 16:13 UTC
Labels: client-config, 1.2.5rev5
